Controllers/SearchController.cs
using System.Web.Mvc;
using Orchard.Localization;
using Orchard;
using Orchard.Themes;
using Orchard.Search.Services;
using Orchard.ContentManagement;
using Orchard.Settings;
using Orchard.DisplayManagement;
using Orchard.Logging;
using Orchard.UI.Navigation;
using Orchard.Search.Models;
using Orchard.Indexing;
using Orchard.Collections;
using Orchard.Search.Helpers;
using System;
using Orchard.Search.ViewModels;
using System.Linq;
using Orchard.UI.Notify;

namespace Datwendo.SearchMenu.Controllers {

    [ValidateInput(false), Themed]
    public class SearchController : Controller
    {
        private readonly ISearchService _searchService;
        private readonly IContentManager _contentManager;
        private readonly ISiteService _siteService;

        public SearchController(
            IOrchardServices services,
            ISearchService searchService,
            IContentManager contentManager,
            ISiteService siteService,
            IShapeFactory shapeFactory)
        {

            Services = services;
            _searchService = searchService;
            _contentManager = contentManager;
            _siteService = siteService;

            T = NullLocalizer.Instance;
            Logger = NullLogger.Instance;
            Shape = shapeFactory;
        }

        private IOrchardServices Services { get; set; }
        public Localizer T { get; set; }
        public ILogger Logger { get; set; }
        dynamic Shape { get; set; }

        public ActionResult Index(PagerParameters pagerParameters, string searchIndex = null, string q = "")
        {
            var pager = new Pager(_siteService.GetSiteSettings(), pagerParameters);
            var searchSettingPart = Services.WorkContext.CurrentSite.As<SearchSettingsPart>();
            var index = !String.IsNullOrWhiteSpace(searchIndex) ? searchIndex.Trim() : searchSettingPart.SearchIndex;

            if (String.IsNullOrEmpty(index))
            {
                Services.Notifier.Error(T("Please define a default search index."));
                return HttpNotFound();
            }

            IPageOfItems<ISearchHit> searchHits = new PageOfItems<ISearchHit>(new ISearchHit[] { });
            try
            {
                searchHits = _searchService.Query(
                    q, pager.Page, pager.PageSize,
                    Services.WorkContext.CurrentSite.As<SearchSettingsPart>().FilterCulture,
                    index,
                    searchSettingPart.GetSearchFields(index),
                    searchHit => searchHit);
            }
            catch (Exception exception)
            {
                Logger.Error(T("Invalid search query: {0}", exception.Message).Text);
                Services.Notifier.Error(T("Invalid search query: {0}", exception.Message));
            }

            var list = Shape.List();
            var foundIds = searchHits.Select(searchHit => searchHit.ContentItemId).ToList();

            // ignore search results which content item has been removed or unpublished
            var foundItems = _contentManager.GetMany<IContent>(foundIds, VersionOptions.Published, new QueryHints()).ToList();
            foreach (var contentItem in foundItems)
            {
                list.Add(_contentManager.BuildDisplay(contentItem, searchSettingPart.DisplayType));
            }
            searchHits.TotalItemCount -= foundIds.Count() - foundItems.Count();

            var pagerShape = Shape.Pager(pager).TotalItemCount(searchHits.TotalItemCount);

            var searchViewModel = new SearchViewModel
            {
                Query = q,
                TotalItemCount = searchHits.TotalItemCount,
                StartPosition = (pager.Page - 1) * pager.PageSize + 1,
                EndPosition = pager.PageSize == 0 || (pager.Page * pager.PageSize > searchHits.TotalItemCount ) ? searchHits.TotalItemCount : pager.Page * pager.PageSize,
                ContentItems = list,
                Pager = pagerShape
            };

            //todo: deal with page requests beyond result count

            return View(searchViewModel);
        }
    }
}

Views/MenuItemLink-SearchMenuItem.cshtml
@using Orchard.ContentManagement
@using Orchard.Search.Models
@using Orchard.Search.ViewModels;
@{
    var settings = WorkContext.CurrentSite.As<SearchSettingsPart>();
    var part = (SearchFormPart)Model.Content.SearchFormPart;
    var index = part.OverrideIndex && part.SelectedIndex != settings.SearchIndex ? part.SelectedIndex : default(string);
    var routeValues = new RouteValueDictionary { { "area", "Orchard.Search" } };

    if (!String.IsNullOrEmpty(index))
    {
        routeValues.Add("searchIndex", index);
    }
    var vm = new SearchViewModel();
}
@using (Html.BeginForm("Index", "Search", routeValues, FormMethod.Get, new RouteValueDictionary { { "class", "search-form" } }))
{
    <div class="input-group">
        @Html.TextBox("q", vm.Query, new { @class = "input-medium", placeholder = "Search" })
        @Html.Hidden("culture", WorkContext.CurrentCulture)
        <button type="submit" class="btn"><i class="icon-search"></i></button>
    </div>
}

Views/Search/Index.cshtml
@model Orchard.Search.ViewModels.SearchViewModel
@{
    Style.Require("Search");

    IEnumerable<object> searchResults = Model.ContentItems;
    Model.ContentItems.Classes.Add("content-items");
    Model.ContentItems.Classes.Add("search-results");
}
<h1>@Html.TitleForPage(T("Search").Text)</h1>

@if (HasText(Model.Query)) {
    if (!searchResults.Any()) { 
        <p class="search-summary">@T.Plural("There is <em>one</em> result", "<em>zero</em> results", searchResults.Count())</p>
    } else { 
        <p class="search-summary">@T.Plural("There is <em>one</em> result", "<em>{1} - {2}</em> of <em>{0}</em> results", Model.TotalItemCount, Model.StartPosition, Model.EndPosition)</p>
    }
}
@if (searchResults != null && searchResults.Any()) {
    @Display(searchResults)
    @Display(Model.Pager)
} 